version: "3"
services:
  mongodb_test_keepcoding:
    image: mongo
    container_name: keepcoding_test_mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - './data:/data/db'
      - './data:/data/configdb'
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 27017:27017
    restart: always
